export { customerNotes };

const customerNotes = [
    "Customer wanted to return a used toilet brush. Nope, not touching that.",
    "Customer complained that our store doesn't have a drive-thru. Because shopping for groceries is just like ordering fast food, right?",
    "Customer asked if we sold magic wands. Sorry, Hogwarts is down the street.",
    "Customer demanded a refund on a can of air because 'it didn't smell like roses'. Seriously?",
    "Customer insisted on returning a half-eaten sandwich because 'it wasn't what they expected'. Maybe next time try reading the menu?",
    "Customer got mad because we didn't have their favorite brand of water. Because apparently, all water tastes the same?",
    "Customer wanted a discount on a scratched CD because 'it skipped'. Um, that's what happens when you scratch a CD.",
    "Customer asked if we sold invisibility cloaks. I told them if we did, they wouldn't be able to find them.",
    "Customer complained that our store's music was too loud. Sorry, we'll turn down the volume on our non-existent DJ.",
    "Customer demanded a refund on a bottle of shampoo because 'it made their hair too clean'. Yeah, that's kind of the point.",
    "Customer asked if we sell unicorns. I told them we're fresh out, but we do have some fairy dust in aisle 3.",
    "Customer demanded a discount because they 'accidentally' dropped their phone in the toilet. Sorry, not covered under our 'clumsy customer' policy.",
    "Customer complained that our store doesn't have a helipad. Yes, because every retail store needs one, right?",
    "Customer asked for a refund on a used toothbrush because 'it didn't make their teeth whiter instantly'. Sorry, we're not miracle workers.",
    "Customer wanted to return a bag of opened chips because 'they weren't crunchy enough'. Seriously?",
    "Customer demanded to speak to the manager because we ran out of their favorite color of socks. Because, you know, it's totally our fault.",
    "Customer insisted on a refund for a plant they killed because they 'didn't know it needed water'. Maybe stick to cacti next time?",
    "Customer asked if we sell time machines. I told them no, but we do have a great selection of calendars.",
    "Customer wanted a discount on a scratched DVD because it 'ruined the movie experience'. Spoiler alert: It was already in the bargain bin.",
    "Customer wanted a refund on a bottle of sunscreen because 'it didn't prevent them from getting sunburned'. Maybe try applying it next time?",
    "Customer demanded a refund on a can of expired beans. I guess they were expecting gourmet dining from a discount store.",
    "Customer got upset because we wouldn't accept their coupon from 1995. Sorry, we're not a time capsule.",
    "Customer complained that our free Wi-Fi was too slow. Newsflash: It's free for a reason.",
    "Customer asked for a discount on a perfectly good laptop because they found a cheaper one online. Good luck with that shipping fee.",
    "Customer insisted on returning a half-eaten pizza because 'it wasn't what they expected'. What were you expecting, a pizza party in your mouth?",
    "Customer demanded a refund on a bag of ice because 'it melted'. Uh, that's kind of what ice does.",
    "Customer wanted to return a book because 'it didn't match their sofa'. I guess books aren't just for reading anymore.",
    "Customer got mad because we didn't have their size in a shirt they liked. Sorry, we can't cater to every body shape AND fashion trend.",
    "Customer asked if we sold flying cars. I told them no, but we have plenty of regular ones that'll get you from A to B.",
    "Customer complained that our sale items weren't cheap enough. Maybe try a thrift store next time?",
    "Customer went on a rant about how our store's layout 'ruined their shopping experience'. Apparently, we're responsible for their lack of direction.",
    "Customer wrote a scathing review because we ran out of their favorite brand of soda. Sorry, but we're not psychic - we can't predict your soda cravings.",
    "Customer threatened to boycott our store because we don't carry their obscure dietary supplement. Guess they'll have to get their daily dose of unicorn tears elsewhere.",
    "Customer demanded compensation for a 'traumatizing' shopping experience. Apparently, seeing a spider in aisle 7 qualifies as a national emergency.",
    "Customer claimed they found a mouse in their bag of chips and demanded a lifetime supply of snacks. Nice try, but we're not falling for your rodent-related shenanigans.",
    "Customer insisted on returning a pair of shoes they wore to a mud run. Sorry, but 'destroyed by mud' isn't covered under our return policy.",
    "Customer got into a shouting match with a cashier over a 5-cent price difference. Because clearly, 5 cents is worth losing your dignity over.",
    "Customer threatened to sue because our store didn't have an escalator. Apparently, walking up a flight of stairs is just too much effort.",
    "Customer complained that our store's lighting was 'too bright'. Because, you know, being able to see what you're buying is such a hassle.",
    "Customer demanded a refund on a bag of coffee because 'it didn't taste like it does at Starbucks'. Sorry, but we're not baristas - we just sell the stuff.",
    "Customer threatened to leave a bad review because we don't offer valet parking. Sorry, we're not a five-star hotel.",
    "Customer complained that our store's air conditioning was 'too cold'. Because apparently, we should cater to their personal thermostat preferences.",
    "Customer demanded a refund on a bag of chips because 'they weren't as crunchy as the ones they had as a kid'. Sorry, we can't turn back time.",
    "Customer asked for a discount on a laptop because 'it didn't match their aura'. Whatever you say, psychic.",
    "Customer insisted on returning a shirt they wore to a concert. Sorry, but 'sweaty rock concert attire' isn't covered under our return policy.",
    "Customer got upset because we didn't have their favorite flavor of gum. Because obviously, we should have a gum sommelier on staff.",
    "Customer wanted to return a dog bed because 'their dog didn't like it'. I'm sure your dog is just holding out for a memory foam mattress.",
    "Customer complained that our store's lighting was 'too dim'. Sorry, we're not a nightclub.",
    "Customer demanded a refund on a bag of frozen vegetables because 'they didn't taste fresh'. Maybe next time try buying fresh vegetables?",
    "Customer asked if we sold jetpacks. I told them no, but we have some nice sneakers.",
    "Customer wrote a complaint letter about our store's lack of a rooftop garden. Because apparently, they want to do some urban farming while they shop.",
    "Customer went on a tirade about our store's lack of gluten-free, vegan, organic, non-GMO, sustainably sourced, fair-trade, artisanal, handcrafted, locally made, zero-waste, carbon-neutral products. Because obviously, we're not catering to their very specific dietary preferences.",
    "Customer threatened to stage a protest outside our store because we don't offer valet parking. Sorry, but we're not rolling out the red carpet for your Honda Civic.",
    "Customer complained that our store doesn't have a helipad. Because obviously, arriving by helicopter is the only acceptable mode of transportation.",
    "Customer demanded compensation for a 'traumatic' shopping experience. Apparently, our lack of unicorn-themed merchandise was deeply upsetting.",
    "Customer got into a heated argument with a cashier over a 10-cent price difference. Because clearly, 10 cents is worth going to battle over.",
    "Customer threatened to call the Better Business Bureau because we didn't have their favorite brand of cereal. Because obviously, this is a matter of national importance.",
    "Customer complained that our store's lack of live music made their shopping experience 'boring'. Sorry, but we're not hosting a concert every time you need to buy toothpaste.",
    "Customer wrote a strongly worded email about our store's lack of a petting zoo. Because apparently, shopping for groceries should come with a side of llama cuddles.",
    "Customer demanded a refund on a bag of ice because 'it melted'. Newsflash: That's what happens when you put ice in a warm environment.",
    "Customer asked if we sell unicorns. I told them we're fresh out, but we do have some fairy dust in aisle 3.",
    "Customer demanded a discount because they 'accidentally' dropped their phone in the toilet. Sorry, not covered under our 'clumsy customer' policy.",
    "Customer complained that our store doesn't have a helipad. Yes, because every retail store needs one, right?",
    "Customer asked for a refund on a used toothbrush because 'it didn't make their teeth whiter instantly'. Sorry, we're not miracle workers.",
    "Customer wanted to return a bag of opened chips because 'they weren't crunchy enough'. Seriously?",
    "Customer demanded to speak to the manager because we ran out of their favorite color of socks. Because, you know, it's totally our fault.",
    "Customer insisted on a refund for a plant they killed because they 'didn't know it needed water'. Maybe stick to cacti next time?",
    "Customer asked if we sell time machines. I told them no, but we do have a great selection of calendars.",
    "Customer wanted a discount on a scratched DVD because it 'ruined the movie experience'. Spoiler alert: It was already in the bargain bin.",
    "Customer wanted a refund on a bottle of sunscreen because 'it didn't prevent them from getting sunburned'. Maybe try applying it next time?",
    "Customer demanded a discount on a wrinkled shirt because 'it's the last one in their size'. Sorry, our clothes aren't ironed by magic elves.",
    "Customer asked if we sell teleportation devices. I told them no, but we do have some nice shoes that can take you places.",
    "Customer complained that our store doesn't have valet parking. Because, you know, parking your own car is just too much effort.",
    "Customer insisted on returning a chewed-up dog toy because 'their dog didn't like it'. Maybe your dog is just a picky chewer?",
    "Customer wanted a refund on a bag of expired candy because 'it didn't taste fresh'. Newsflash: Candy doesn't get better with age.",
    "Customer asked if we sell magic beans. I told them no, but we do have some excellent coffee beans.",
    "Customer complained that our store's Wi-Fi was too slow. Sorry, we can't control the internet.",
    "Customer demanded a refund on a broken mirror because 'it gave them bad luck'. Maybe you should stop walking under ladders.",
    "Customer asked if we sell jetpacks. I told them no, but we have some nice umbrellas in case it rains.",
    "Customer wanted to return a used yoga mat because 'it didn't make them instantly flexible'. Sorry, yoga takes time and effort.",
    "Customer insisted on returning a half-eaten sandwich because 'it wasn't what they expected'. What were you expecting, a gourmet meal?",
    "Customer threatened to leave a bad review because we don't offer valet parking. Sorry, we're not a five-star hotel.",
    "Customer complained that our store's air conditioning was 'too cold'. Because apparently, we should cater to their personal thermostat preferences.",
    "Customer demanded a refund on a bag of chips because 'they weren't as crunchy as the ones they had as a kid'. Sorry, we can't turn back time.",
    "Customer asked for a discount on a laptop because 'it didn't match their aura'. Whatever you say, psychic.",
    "Customer insisted on returning a shirt they wore to a concert. Sorry, but 'sweaty rock concert attire' isn't covered under our return policy.",
    "Customer got upset because we didn't have their favorite flavor of gum. Because obviously, we should have a gum sommelier on staff.",
    "Customer wanted to return a dog bed because 'their dog didn't like it'. I'm sure your dog is just holding out for a memory foam mattress.",
    "Customer complained that our store's lighting was 'too dim'. Sorry, we're not a nightclub.",
    "Customer demanded a refund on a bag of frozen vegetables because 'they didn't taste fresh'. Maybe next time try buying fresh vegetables?",
    "Customer asked if we sold jetpacks. I told them no, but we have some nice sneakers that'll make you feel like you're flying.",
    "Customer wanted to return a used toothbrush because 'it didn't make their teeth whiter instantly'. Maybe invest in some toothpaste?",
    "Customer complained that our store doesn't have valet parking. Because, you know, walking is just too much effort.",
    "Customer asked if we sell invisibility cloaks. I told them if we did, they wouldn't be able to find them.",
    "Customer demanded a discount on a scratched DVD because 'it ruined the movie experience'. Spoiler alert: It was already in the bargain bin.",
    "Customer wanted a refund on a bottle of sunscreen because 'it didn't prevent them from getting sunburned'. Maybe try applying it next time?",
    "Customer asked if we sell teleportation devices. I told them no, but we do have some nice shoes that can take you places.",
    "Customer complained that our store doesn't have valet parking. Because, you know, parking your own car is just too much effort.",
    "Customer wrote a complaint letter about our store's lack of a rooftop garden. Because apparently, they want to do some urban farming while they shop.",
    "Customer went on a tirade about our store's lack of gluten-free, vegan, organic, non-GMO, sustainably sourced, fair-trade, artisanal, handcrafted, locally made, zero-waste, carbon-neutral products. Because obviously, we're not catering to their very specific dietary preferences.",
    "Customer threatened to stage a protest outside our store because we don't offer valet parking. Sorry, but we're not rolling out the red carpet for your Honda Civic.",
    "Customer complained that our store doesn't have a helipad. Because obviously, arriving by helicopter is the only acceptable mode of transportation.",
    "Customer demanded compensation for a 'traumatic' shopping experience. Apparently, our lack of unicorn-themed merchandise was deeply upsetting.",
    "Customer got into a heated argument with a cashier over a 10-cent price difference. Because clearly, 10 cents is worth going to battle over.",
    "Customer threatened to call the Better Business Bureau because we didn't have their favorite brand of cereal. Because obviously, this is a matter of national importance.",
    "Customer complained that our store's lack of live music made their shopping experience 'boring'. Sorry, but we're not hosting a concert every time you need to buy toothpaste.",
    "Customer wrote a strongly worded email about our store's lack of a petting zoo. Because apparently, shopping for groceries should come with a side of llama cuddles.",
    "Customer demanded a refund on a bag of ice because 'it melted'. Newsflash: That's what happens when you put ice in a warm environment.",
    "Customer complained that our store doesn't have valet parking. Because, you know, walking is just too much effort.",
    "Customer asked if we sell invisibility cloaks. I told them if we did, they wouldn't be able to find them.",
    "Customer demanded a discount on a scratched DVD because 'it ruined the movie experience'. Spoiler alert: It was already in the bargain bin.",
    "Customer wanted a refund on a bottle of sunscreen because 'it didn't prevent them from getting sunburned'. Maybe try applying it next time?",
    "Customer asked if we sell teleportation devices. I told them no, but we do have some nice shoes that can take you places.",
    "Customer complained that our store doesn't have valet parking. Because, you know, parking your own car is just too much effort.",
    "Customer insisted on returning a chewed-up dog toy because 'their dog didn't like it'. Maybe your dog is just a picky chewer?",
    "Customer wanted a refund on a bag of expired candy because 'it didn't taste fresh'. Newsflash: Candy doesn't get better with age.",
    "Customer asked if we sell magic beans. I told them no, but we do have some excellent coffee beans.",
    "Customer complained that our store's Wi-Fi was too slow. Sorry, we can't control the internet.",
    "Customer demanded a refund on a broken mirror because 'it gave them bad luck'. Maybe you should stop walking under ladders.",
    "Customer wrote a complaint letter about our store's lack of a rooftop garden. Because apparently, they want to do some urban farming while they shop.",
    "Customer went on a tirade about our store's lack of gluten-free, vegan, organic, non-GMO, sustainably sourced, fair-trade, artisanal, handcrafted, locally made, zero-waste, carbon-neutral products. Because obviously, we're not catering to their very specific dietary preferences.",
    "Customer threatened to stage a protest outside our store because we don't offer valet parking. Sorry, but we're not rolling out the red carpet for your Honda Civic.",
    "Customer complained that our store doesn't have a helipad. Because obviously, arriving by helicopter is the only acceptable mode of transportation.",
    "Customer demanded compensation for a 'traumatic' shopping experience. Apparently, our lack of unicorn-themed merchandise was deeply upsetting.",
    "Customer got into a heated argument with a cashier over a 10-cent price difference. Because clearly, 10 cents is worth going to battle over.",
    "Customer threatened to call the Better Business Bureau because we didn't have their favorite brand of cereal. Because obviously, this is a matter of national importance.",
    "Customer complained that our store's lack of live music made their shopping experience 'boring'. Sorry, but we're not hosting a concert every time you need to buy toothpaste.",
    "Customer wrote a strongly worded email about our store's lack of a petting zoo. Because apparently, shopping for groceries should come with a side of llama cuddles.",
    "Customer asked if we sell time machines. I told them no, but we do have a great selection of calendars.",
    "Customer complained that our store doesn't have a helipad. Yes, because every retail store needs one, right?",
    "Customer demanded a discount because they 'accidentally' dropped their phone in the toilet. Sorry, not covered under our 'clumsy customer' policy.",
    "Customer asked if we sell unicorns. I told them we're fresh out, but we do have some fairy dust in aisle 3.",
    "Customer wanted to return a bag of opened chips because 'they weren't crunchy enough'. Seriously?",
    "Customer insisted on a refund for a plant they killed because they 'didn't know it needed water'. Maybe stick to cacti next time?",
    "Customer asked for a refund on a used toothbrush because 'it didn't make their teeth whiter instantly'. Sorry, we're not miracle workers.",
    "Customer demanded to speak to the manager because we ran out of their favorite color of socks. Because, you know, it's totally our fault.",
    "Customer wanted a refund on a bottle of sunscreen because 'it didn't prevent them from getting sunburned'. Maybe try applying it next time?",
    "Customer asked for a discount on a scratched DVD because it 'ruined the movie experience'. Spoiler alert: It was already in the bargain bin.",
    "Customer called to inquire about product availability.",
    "Customer visited the store and purchased multiple items.",
    "Customer returned a defective product for a refund.",
    "Customer requested assistance with using a product.",
    "Customer provided positive feedback about the store's cleanliness.",
    "Customer asked about upcoming promotions and sales.",
    "Customer complained about a long wait time at checkout.",
    "Customer requested a price match for a product found cheaper elsewhere.",
    "Customer asked for recommendations for a specific type of product.",
    "Customer complimented a staff member for their helpfulness.",
    "Customer reported an issue with a product purchased online.",
    "Customer requested assistance with assembling a product.",
    "Customer requested a refund for a product they were dissatisfied with.",
    "Customer praised the store's wide selection of products.",
    "Customer requested a catalog be mailed to their address.",
    "Customer expressed frustration with the lack of parking spaces.",
    "Customer requested assistance with finding a specific product in-store.",
    "Customer asked about the return policy for an item purchased as a gift.",
    "Customer provided feedback on the store's website layout.",
    "Customer requested information about upcoming store events.",
    "Customer asked for clarification on a promotion's terms and conditions.",
    "Customer reported receiving excellent service from a staff member.",
    "Customer requested information about product warranties.",
    "Customer requested assistance with selecting a gift for a family member.",
    "Customer complained about an item being out of stock.",
    "Customer requested assistance with locating a product on the website.",
    "Customer praised the store's fast checkout process.",
    "Customer asked about the store's holiday hours.",
    "Customer requested assistance with redeeming a gift card online.",
    "Customer provided feedback on the store's store layout.",
    "Customer expressed interest in signing up for the store's loyalty program.",
    "Customer asked about the store's policy on rain checks for out-of-stock items.",
    "Customer requested assistance with processing a return without a receipt.",
    "Customer complimented the store's knowledgeable staff members.",
    "Customer asked about the store's policy on accepting expired coupons.",
    "Customer reported receiving incorrect change at the checkout.",
    "Customer requested assistance with tracking a package for an online order.",
    "Customer expressed dissatisfaction with the quality of a product purchased.",
    "Customer praised the store's convenient location.",
    "Customer reported difficulty navigating the store's website on their mobile device.",
    "Customer requested assistance with signing up for the store's email newsletter.",
    "Customer asked about the store's policy on price adjustments for recently purchased items.",
    "Customer complained about receiving multiple promotional emails from the store.",
    "Customer requested assistance with troubleshooting a product they purchased.",
    "Customer praised the store's friendly and helpful customer service.",
    "Customer reported receiving damaged merchandise in their online order.",
    "Customer requested assistance with locating a specific product category on the website.",
    "Customer expressed interest in purchasing a product that was currently out of stock.",
    "Customer reported an error on the store's website checkout page.",
    "Customer asked about the store's policy on allowing pets inside.",
    "Customer requested assistance with ordering a product for in-store pickup.",
    "Customer asked about the store's policy on accepting competitor coupons.",
    "Customer complimented the store's clean and organized displays.",
    "Customer requested assistance with downloading the store's mobile app.",
    "Customer reported receiving excellent service from the store manager.",
    "Customer praised the store's efficient returns process.",
    "Customer requested assistance with locating a specific product variant.",
    "Customer asked about the store's policy on returns for online purchases.",
    "Customer expressed interest in receiving notifications about upcoming sales.",
    "Customer reported difficulty logging into their online account.",
    "Customer requested assistance with finding a product that was advertised in a recent flyer.",
    "Customer asked about the store's policy on accepting manufacturer's coupons.",
    "Customer complimented the store's helpful signage for product categories."
];
